### ISSUE TITLE
No option to return percentage values as unformatted fractional number

### ISSUE THREAD

**Issue by ralfstrobel** [AsperaGmbH/xlsx-reader#11]
XLSX files internally represent values such as "20%" as a floating point string like "0.2".
The `NumberFormat` class is currently hardcoded to multiply such values by 100, implicitly casting them to floats.
The "ReturnUnformatted" option does not affect this behavior as it is only checked later in the `formatValue()` method.

Applications may find it useful to read percentage values in their more semantically native fractional representation.
This is also particularly relevant when migrating from the [akeneo-labs/spreadsheet-parser](https://github.com/akeneo-labs/spreadsheet-parser) library, which returns percentages this way. This represents one of the few breaking changes between the akeneo library and this one that cannot be overcome by configuration.

**Comment by rfischer42** [comment]
No problem, we can easily throw in a configuration option to control that behavior as needed.

I need to take care of some other things at the moment, but once that's done, I'll get to work on this.
You can expect the respective update of the library by next week. My gut-feeling says tuesday/wednesday, but this may depend on more than just me.

Since we're already here: Be advised that, with the next update, I intend to slightly rework the way configuration options are supplied to the reader.
The reader will expect an instance of a then-new configuration options class to be supplied to its constructor, instead of a configuration array with key-value pairs, as it is done now. This should aid in reducing problems caused by e.g. typos when trying to specify configuration options.
This will be a breaking change, as it will require you to adjust your usage of the reader in your solution as well. Though since you'll be touching that code for the sake of adding the new configuration option anyway, it shouldn't add much complexity in this case.

I'll keep you updated.

**Comment by ralfstrobel** [comment]
Thanks, that sounds great!

**Comment by rfischer42** [comment]
Quick update: Changes are currently in QA phase, which is unfortunately taking a bit longer than anticipated.
We're working on it though.
Best case, the release will still happen this week. Otherwise, it's looking like sometime next week.

**Comment by rfischer42** [comment]
The update is out now. Please note the breaking changes list noted in the changelog for compatibility. (In particular, the aforementioned changes to the configuration options structure.)

With v0.9.0 installed, to return percentage values in their XLSX-internal representation, configure the reader e.g. as follows:
```php
use Aspera\Spreadsheet\XLSX\Reader;
use Aspera\Spreadsheet\XLSX\ReaderConfiguration;

$reader_config = (new ReaderConfiguration())
    ->setReturnPercentageDecimal(true);

new Reader($reader_config);
```

**Comment by ralfstrobel** [comment]
Works as described. Thanks again!

**Comment by ralfstrobel** [comment]
I've discovered another gotcha to this newly intoduced mode. Some floating point values may be internally stored in E-notation, even if the number is not very large or small (e.g. "7.0000000000000007E-2") due to rounding errors. So whatever parser is reading in the unformatted numbers must be compatible with this format.

**Comment by rfischer42** [comment]
You are correct. The formatting tends to hide a lot of these kinds of issues.
For what it's worth, the next release will contain a note about this in the documentation of the relevant configuration options.
Thank you for pointing it out here.
