### ISSUE TITLE
Please support number formats [$-F400] and [$-F800]

### ISSUE THREAD

**Issue by SaschaKliche** [AsperaGmbH/xlsx-reader#17]
Hi, I have received multiple XLSX files that contain the number format code `[$-F400]h:mm:ss\ AM/PM`. According to the Ecma Office Open XML specification the `F400` code is used for "System time format". There is also an `F800` code for "System long date format".

Trying to load the file with this number format fails in [NumberFormatTokenizer.php:753](https://github.com/AsperaGmbH/xlsx-reader/blob/9e273054e746c455ea334f901b8da1af147e0ee8/lib/NumberFormatTokenizer.php#L753). The regex in [line 751](https://github.com/AsperaGmbH/xlsx-reader/blob/9e273054e746c455ea334f901b8da1af147e0ee8/lib/NumberFormatTokenizer.php#L751) doesn't match this format so the next call that tries to access `$matches[1]` results in `Undefined array key 1`.
Extending the regex to include an optional F (`\$([^-]*)-[fF]?\d+`) would fix it and the unit tests would still pass even though you might want to handle it differently to be able to apply the correct format.

It would be nice if you could add support for those format codes.

Thank you for providing this helpful library!

**Comment by rfischer42** [comment]
Greetings,

With the newest release (v1.1.0) the reader should no longer throw errors when given a file using format specifications such as this one.

Note that this does not add *full* support for date/time formatting based on locale, despite this technically being the point of the 0xf400/0xf800 format codes. This form of locale information has gone ignored thus far, as there hasn't been an explicit request for this functionality yet.

This is because, for various reasons, it may be more beneficial for the consuming code to either:
- enforce a consistent date/time format (via ReaderConfiguration::setForceDateFormat(), ::setForceTimeFormat() and/or ::setForceDateTimeFormat())
- use DateTime objects instead (see ReaderConfiguration::setReturnDateTimeObjects())

If, despite of that, you happen to require the current system format to be applied correctly (which may or may not match that of the user that initially wrote the XLSX file), please open another ticket for it, which we would then treat as a feature request.
Otherwise, everything should work fine now.

Thank you for the report, and take care.
