### ISSUE TITLE
Bug; multi-sectioned formats are exploded incorrectly...

### ISSUE THREAD

**Issue by AzzaAzza69** [AsperaGmbH/xlsx-reader#7]
your code:
                $sections = explode(';', $format['Code']);

doesn't handle if the ";" is quoted - I suggest:
	        $sections = preg_split('/(;)(?=(?:[^"]|"[^"]*")*$)/u', $format['Code']);	// up to four sections, separated with an (unquoted) semi-colon

**Comment by rfischer42** [comment]
Hello Azza,

Can confirm, this is not handled.
Thank you for your report, a fix is in the making.

And thank you for your fix suggestion, too.
Fair warning though, I cannot guarantee that your suggestion will actually make it into the finalized fix, due to more problems having been discovered in this section that require more extensive code changes.
We'll be looking into those.

**Comment by rfischer42** [comment]
With the just-released version, format section splitting should now occur as expected.
