### ISSUE TITLE
how to disable remove repeat cell value?

### ISSUE THREAD

**Issue by yunmoxue** [AsperaGmbH/xlsx-reader#8]
my execel data is 
```
A,B,C,D,E
1,london,london,DEC,12345
```
when i get by reader 
```
        $reader = new Reader($options);
        $reader->open($tempFile);

        $data = [];
        foreach ($reader as $row) {
            var_dump($row);
            if (empty(implode('', $row))) {
                continue;
            } else {
                $data[] = $row;
            }
        }
```
the dump is 
```
['A', 'B', 'C', 'D', 'E']
['1', 'london', 'DEC', '', 12345]
```

how to get the full data?
```
['1', 'london', 'london', 'DEC', 12345]
```
Thanks

**Comment by rfischer42** [comment]
Hey there,

I'm sorry, but I can't seem to reproduce this issue on the current master. :/

Can you attach the/an XLSX file that causes this issue on your end? Perhaps it's got something to do with the file itself, rather than its plain data.

Also, I noticed that you didn't include the declaration for $options in your code snippet.
Are you setting any particular $options by chance, which might be needed to reproduce the issue?

**Comment by rfischer42** [comment]
Closed due to inactivity.
